"""Metodos_Numericos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uXOTUQ5XFYEuTTZB5p7341DYGO0o0YuW
"""

import matplotlib.pyplot as plt

"""**Problema**: Encontrar la raíz cuadrada de 2 usando el método de **Busqueda Incremental **

$$
\\
\\
f(x)=(x-1)^2-2=0
$$
"""

def FunctionEval(function:str,x0):
    Evalfunc = function.replace("x",str(x0))
    return eval(Evalfunc)

def SearchIncremental(func,x0,delta,iter):
  '''
  El metodo de Busqueda incremental  es un método cerrado para resolver ecuaciones no lineales
  los argumentos son:
  Entrada
  -------
       f : Ecuación a resolver expresada en la forma f(x)=0
       x0: Intervalo inferior 
     delta : Incremento delta  
  Salida
  ------
      x : Raíz de la ecuación
  tabla : Tabla de iteraciones
  '''
  Nraices=0 
  fx0 = FunctionEval(func,x0)
  x1= x0 + delta # Incremento para encontrar el primer intervalo
  fx1 = FunctionEval(func,x1)
  table = {}
  if fx0==0:
    print("La raiz esta en X0={}, si fx(0) es igual a cero entonces x0 es la raiz ".format(x0))
  else:
    i=0 
  while  (fx0 * fx1) > 0 and  i < iter :
    x0=x1 
    fx0=fx1 
    x1= x0+delta
    fx1=FunctionEval(func,x1)
    i=i+1

  table["fx0"] = fx0
  table["fx1"] = fx1
  table["x0"] = x0
  table["x1"] = x1
  table["iter"] = iter

  if fx1:
    table["txt"] = f"x1 es raiz {x1}"
  elif fx1 * fx0 < 0:
    table["txt"] = f"entre X0={x0} y X1={x1} hay almenos una raiz"
  else:
    table["txt"] = "No hay solucion"
  return table

#SearchIncremental("(x-1)**2-2",-1,0.5,32)

#help(SearchIncremental)